##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 11111

###################  spring配置  ###################
spring:
  profiles:
    active: dev

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

logging:
  level:
    root: INFO
    org:
      tang: DEBUG
  path: ./logs/dev/


#####################################################################
########################  测试环境profile  ##########################
#####################################################################

spring:
  profiles: test

logging:
  level:
    ROOT: INFO
    org:
      tang: DEBUG
  file: ./logs/test/
