##########################################################
##################  所有profile共有的配置  #################
##########################################################

###################  项目启动端口  ###################
server.port: 11111

###################  spring配置  ###################
spring:
  profiles:
    active: dev

#####################################################################
########################  开发环境profile  ##########################
#####################################################################
spring:
  profiles: dev

###################  mybatis-plus配置  ###################
mybatis-plus:
  mapper-locations: classpath*:org/tang/springboot/dao/repository/mapping/*.xml
  typeAliasesPackage: >
    org.tang.springboot.dao.entity
  global-config:
    id-type: 3  # 0:数据库ID自增   1:用户输入id  2:全局唯一id(IdWorker)  3:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性

spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useSSL=false&autoReconnect=true&tinyInt1isBit=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456

spring:
  profiles: dev
  cache:
    type: REDIS
    redis:
      cache-null-values: false
      time-to-live: 600000ms
      use-key-prefix: true
    cache-names: userCache,allUsersCache
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    lettuce:
      shutdown-timeout: 200ms
      pool:
        max-active: 7
        max-idle: 7
        min-idle: 2
        max-wait: -1ms

spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb://xiongneng:123456@localhost:27017/test

spring:
  profiles: dev
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: spring
    password: 123456
    publisher-confirms: true #支持发布确认
    publisher-returns: true  #支持发布返回
    listener:
      simple:
        acknowledge-mode: manual #采用手动应答
        concurrency: 1 #指定最小的消费者数量
        max-concurrency: 1 #指定最大的消费者数量
        retry:
          enabled: true #是否支持重试


httpclient:
  connectTimeout: 20000
  requestTimeout: 20000
  socketTimeout: 30000
  defaultMaxPerRoute: 100
  maxTotalConnections: 300
  defaultKeepAliveTimeMillis: 20000
  closeIdleConnectionWaitTimeSecs: 30



logging:
  level:
    root: INFO
    org:
      tang: DEBUG
  path: ./logs/dev/


#####################################################################
########################  测试环境profile  ##########################
#####################################################################

spring:
  profiles: test

logging:
  level:
    ROOT: INFO
    org:
      tang: DEBUG
  file: ./logs/test/
